config/routes.rb
Barcamp::Application.routes.draw do
 

 
  
  resources :conferences do 
    resources :workshops
    resources :rooms
  end

  root :to => 'conferences#index'

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  attr_accessible :name, :organizer, :room, :session, :start_date, :start_time
  has_many :workshops
 
  #validates :name, :organizer, :room, :session, :presence => true
  #validates :room, :numericality => {:greater_than_or_equal_to => 0.01}
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :floor, :name, :seat, :conference_id
 
  has_many :workshops
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
  attr_accessible :name, :talker, :conference_id, :start_time, :end_time, :room_id
  belongs_to :conference
  belongs_to :room
  validates :name, presence: true
 # accepts_nested_attributes_for :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

     private
def current_conference 
	conference.find(session[:conference_id])
	rescue ActiveRecord::RecordNotFound 
	conference = conference.create 
	session[:cart_id] = conference.id
cart
end

end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = Conference.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conferences }
    end
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
    @conference = Conference.find(params[:id])
    @rooms = Room.all  
    @workshops = Workshop.where(conference_id: params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conference }
    end
  end

  # GET /conferences/new
  # GET /conferences/new.json
  def new
    @conference = Conference.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conference }
    end
  end 

  # GET /conferences/1/edit
  def edit
    @conference = Conference.find(params[:id])

    @workshops = Workshop.where(conference_id: params[:id])
  end

  # POST /conferences
  # POST /conferences.json
  def create
Rails.logger.info "Alarm"
    @conference = Conference.new(params[:conference])
Rails.logger.info "Alarm2 #{@conference.inspect}"
    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render json: @conference, status: :created, location: @conference }
      else
        format.html { render action: "new" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conferences/1
  # PUT /conferences/1.json
  def update
    @conference = Conference.find(params[:id])

    respond_to do |format|
      if @conference.update_attributes(params[:conference])
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference = Conference.find(params[:id])
    @conference.destroy

    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
      @room = Room.new(conference_id: params[:conference_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
         format.html do 
         redirect_to conference_room_path(:conference_id => @room.conference_id, 
                                               :id => @room.id), 
                                         notice: 'Room was successfully created.'
         end
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
        if @room.update_attributes(params[:room])
      
        format.html do
          redirect_to conference_room_path(:conference_id => @room.conference_id, 
                                               :id => @room.id), 
            notice: 'Workshop was successfully updated.' 
         end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to conference_path(@room.conference_id) }
      format.json { head :no_content }
    end
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController



  def show
   @workshop = Workshop.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workshop }
    end
  end

  def new
    @workshop = Workshop.new(conference_id: params[:conference_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workshop }
    end
  end

  # GET /workshops/1/edit
  def edit
    @workshop = Workshop.find(params[:id])
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(params[:workshop])
    respond_to do |format|
      if @workshop.save
        format.html do 
          redirect_to conference_workshop_path(:conference_id => @workshop.conference_id, 
                                               :id => @workshop.id), 
            notice: 'Workshop was successfully created.' 
        end
        format.json { render json: @workshop, status: :created, location: @workshop }
      else
        format.html { render action: "new" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workshops/1
  # PUT /workshops/1.json
  def update
   
    @workshop = Workshop.find(params[:id])
  
    respond_to do |format|
      if @workshop.update_attributes(params[:workshop])
      
        format.html do
          redirect_to conference_workshop_path(:conference_id => @workshop.conference_id, 
                                               :id => @workshop.id), 
            notice: 'Workshop was successfully updated.' 
         end
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
   
    @workshop = Workshop.find(params[:id])
       
    @workshop.destroy
   

    respond_to do |format|
      format.html { redirect_to conference_path(@workshop.conference_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :organizer %><br />
    <%= f.text_field :organizer %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/edit.html.erb
<h1>Editing conference</h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
  

<h1>Barcamp Konferenz</h1>

<table>
  <tr>
    <th>Conference</th>
    <th>Organizer</th>
    <th>Date</th>
    <th>Start date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conferences.each do |conference| %>
  <tr>
    <td><%= conference.name %></td>
    <td><%= conference.organizer %></td>
    
    <td><%= conference.start_date %></td>
    <td><%= conference.start_time.strftime('%H:%M:%S') %></td>
    <td><%= link_to 'Show', conference %></td>
    <td><%= link_to 'Edit', edit_conference_path(conference) %></td>
    <td><%= link_to 'Destroy', conference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

 
<% end %>
</table>

<br />

<%= link_to 'New Conference', new_conference_path %>

app/views/conferences/new.html.erb
<h1>New Barcamp conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<p id="notice"><%= notice %></p>
<div id="top">
<h1>
  <%= @conference.name %>
</h1>
<p>
  <b>organized from:</b>
  <%= @conference.organizer %>
</p>
<p>
  <b>Start date:</b>
  <%= @conference.start_date %>
</p>
<p>
  <b>Start time:</b>
  <%= @conference.start_time.strftime('%H:%M:%S') %>
</p>
 <ul id="Navigation">
<%= link_to 'Home', conferences_path %> |
<%= link_to 'add Workshop', new_conference_workshop_path(conference_id: @conference.id) %>  |
<%= link_to 'add Room', new_conference_room_path(conference_id: @conference.id) %> |
<%= link_to 'edit conference', edit_conference_path(@conference) %> 

</ul>
</div>






    <!--   <th>Seats</th>
      <th>Floor</th>
    </tr> -->
<% @rooms.each do |room| %>
<table>

  <div id="room">
    
    <h2><%= room.name %></h2>
    <p>Seats: <%= room.seat %></p>
    <p>Floor: <%= room.floor %></p>
     <p>ID: <%= room.id %></p>

     <ul id="Navigation">
      <li><%= link_to 'Show', conference_room_path(@conference, id: room.id) %></li>
      <li><%= link_to 'Destroy', conference_room_path(@conference, id: room.id), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <li><%= link_to 'Edit', edit_conference_room_path(@conference, id: room.id) %></li>
    </ul>
    <div id="workshop">
     
    <% @workshops.order("start_time ASC").each do |workshop| %>
    
      <ol><h3>Workshop:</h3> <%= workshop.name %> </ol>
      <ol> <%= workshop.talker %></ol>
      <ol> <%= workshop.start_time.strftime('%H:%M:%S')  %></ol>
      <ol> <%= workshop.end_time.strftime('%H:%M:%S')  %> </ol>
       <%= link_to 'Show', conference_workshop_path(@conference, id: workshop.id) %>
       <%= link_to 'Edit', edit_conference_workshop_path(@conference, id: workshop.id) %>
       <%= link_to 'Destroy', conference_workshop_path(@conference, id: workshop.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    
    <% end %>
  </div>

<% end %>
   </div>
</table>
 


<!-- 

<div>

<table>
  <tr>
    <th>Name</th>
    <th>Talker</th>
    <th>von:</th>
    <th>bis:</th>
    <th></th>
  </tr>
<% @workshops.each do |workshop| %>
  <tr>
    <td><%= workshop.name %>  |</td> 
    <td><%= workshop.talker %>  |</td>
    <td><%= workshop.start_time %>  |</td>
    <td><%= workshop.end_time %>  |</td>
    <td><%= link_to 'Show', conference_workshop_path(@conference, id: workshop.id) %></td>
    <td><%= link_to 'Edit', edit_conference_workshop_path(@conference, id: workshop.id) %></td>
    <td><%= link_to 'Destroy', conference_workshop_path(@conference, id: workshop.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
</div>


 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barcamp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="content">

<%= yield %>
    
 </div> 

</body>
</html>

app/views/rooms/_form.html.erb
<%= form_for [@room.conference, @room] do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= f.hidden_field :conference_id, :value => @room.conference_id %>

  <div class="field">
    <%= f.label :seat %><br />
    <%= f.number_field :seat %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :floor %><br />
    <%= f.text_field :floor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', conference_room_path %> |
<%= link_to 'Back', conference_path(@room.conference_id) %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Seat</th>
    <th>Name</th>
    <th>Floor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.seat %></td>
    <td><%= room.name %></td>
    <td><%= room.floor %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', conference_path(@room.conference_id)  %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Seat:</b>
  <%= @room.seat %>
</p>

<p>
  <b>Name:</b>
  <%= @room.name %>
</p>

<p>
  <b>Floor:</b>
  <%= @room.floor %>
</p>


<%= link_to 'Back', conference_path(@room.conference_id) %>

app/views/workshops/_form.html.erb
  <%= form_for [@workshop.conference, @workshop] do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% @workshop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :conference_id, :value => @workshop.conference_id %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :talker %><br />
    <%= f.text_field :talker %>
  </div>
   <div class="field">
    <%= f.label :start_time %><br />
    <%= f.time_select :start_time %>
  </div>
   <div class="field">
    <%= f.label :end_time %><br />
    <%= f.time_select :end_time %>
  </div>

  <div class="field">
    <%= f.label :Room %>
    <br/>
  
    <%= collection_select(:workshop, :room_id, Room.all, :id, :name, prompt: true) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
 
 
<% end %>

app/views/workshops/edit.html.erb
<h1>Editing workshop</h1>

<%= render 'form' %>

<%= link_to 'Show', conference_workshop_path %>
<%= link_to 'Back', conference_path(@workshop.conference_id) %>

app/views/workshops/new.html.erb
<h1>New workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', conference_path(@workshop.conference_id) %>

app/views/workshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workshop.name %>
</p>

<p>
  <b>Talker:</b>
  <%= @workshop.talker %>
</p>

<%= link_to 'Back', conference_path(@workshop.conference_id) %>
 |